[app]
name = "AnimeStore"
version = "0.0.1"
port = 1212

[database]
host = "localhost"
port = 5432
username = "postgres"
password = ""
name = "animestoredb"
sslmode = "disable"

[cache]
host = "localhost"
port = 6379
password = ""
max_idle = 100
idle_timeout = 5
enabled = true
expire_time = 60
idempotency_expiry = 86400